//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light.WebApi.Core {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Light.WebApi.Core.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NotAllowNull {
            get {
                return ResourceManager.GetString("NotAllowNull", resourceCulture);
            }
        }
        
        internal static string DataLengthError {
            get {
                return ResourceManager.GetString("DataLengthError", resourceCulture);
            }
        }
        
        internal static string DataRangeError {
            get {
                return ResourceManager.GetString("DataRangeError", resourceCulture);
            }
        }
        
        internal static string DataFormatError {
            get {
                return ResourceManager.GetString("DataFormatError", resourceCulture);
            }
        }
        
        internal static string TokenNotExists {
            get {
                return ResourceManager.GetString("TokenNotExists", resourceCulture);
            }
        }
        
        internal static string TokenFormatError {
            get {
                return ResourceManager.GetString("TokenFormatError", resourceCulture);
            }
        }
        
        internal static string TokenError {
            get {
                return ResourceManager.GetString("TokenError", resourceCulture);
            }
        }
        
        internal static string UserTokenError {
            get {
                return ResourceManager.GetString("UserTokenError", resourceCulture);
            }
        }
        
        internal static string UserNotLogin {
            get {
                return ResourceManager.GetString("UserNotLogin", resourceCulture);
            }
        }
        
        internal static string UserHasLogin {
            get {
                return ResourceManager.GetString("UserHasLogin", resourceCulture);
            }
        }
        
        internal static string UserNotPermission {
            get {
                return ResourceManager.GetString("UserNotPermission", resourceCulture);
            }
        }
    }
}
